#!/usr/bin/env bash
# ~/.bash_aliases


# ---------------------------------------------------------------------- 
# ENCRYPTION
# ---------------------------------------------------------------------- 
# GPG Encryption
# Simple symmetric encryption
# alias gpg-encrypt='gpg --symmetric'
# alias gpg-decrypt='gpg --decrypt '
# Advanced symmetric encryption
alias gpg-encrypt='gpg        \
    --symmetric               \
    --cipher-algo aes256      \
    --digest-algo sha512      \
    --cert-digest-algo sha512 \
    --compress-algo none -z 0 \
    --s2k-mode 3              \
    --s2k-digest-algo sha512  \
    --s2k-count 65011712      \
    --force-mdc               \
    --pinentry-mode loopback  \
    --armor                   \
    --no-symkey-cache         \
'
# --output encrypted.gpg \

alias gpg-decrypt='gpg       \
    --decrypt                \
    --pinentry-mode loopback \
    --armor                  \
'
# --output somefile.gpg \

# ---------------------------------------------------------------------- 
# DISPLAY
# ---------------------------------------------------------------------- 

alias choose-primary-monitor='xrandr --listactivemonitors \
  | tail -n +2                                            \
  | cut -d " " -f6                                        \
  | rofi -dmenu                                           \
  | xargs -I% xrandr --output % --primary
'

alias lang='echo "us \nes" \
  | rofi -dmenu             \
  | xargs -I% setxkbmap %
'

# ---------------------------------------------------------------------- 
# PYTHON
# ---------------------------------------------------------------------- 
alias pipup='pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'


# ---------------------------------------------------------------------- 
# SHORTCUTS
# ---------------------------------------------------------------------- 
# Make aliases work with "sudo": https://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo
# We can tell bash to check the next word after the alias (i.e sudo) by adding a space to the end of the alias value.
alias sudo='sudo '

# Shell helpers
# update & upgrade & autoremove
alias uua='sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y'
alias uvim='neovim +PackUpdate +qall ; neovim +CocInstall +qall';
alias vim='nvim';
alias vi='nvim';
alias v='nvim';

# rerun last command as root
alias please='sudo !!'

# some more aliases
# Spelling mistakes
alias ..='cd ..'
alias cd..='cd ..'
alias mode='(set -o | grep emacs.*on >/dev/null 2>&1 && echo "emacs mode" || echo "vi mode")'

# ls shortcuts
# alias l='ls -CF'
# # alias l='ls -l'
# alias ll='ls -AlF'
# alias la='ls -A'
# # alias la='ls -Al'
# alias lss='ls -lAsh'

# Like rm, but safer since it uses trash-cli
alias tp=trash-put
alias rm=trash-put
alias tp-restore=trash-restore

# Like cat, but nicer (needs cat)
# alias cat='bat --style=plain'
alias cat='batcat --style=plain'

# Like ls, but nicer
alias l='exa'
alias la='exa -a'
alias ll='exa -lah'
alias ls='exa --color=auto'

# tree with color
# alias tree='tree -C'
# alias trls='tree -C | less -R'	# -C outputs colour, -R makes less understand color
# using exa as the tree

# Like tree, but nicer (needs exa)
alias tree='exa --tree'

# Like less, but adds better highlighting (needs source-highlight)
alias lessh='LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s" less -M '
# export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# Find big files/directories
alias space-left=baobab

# Copy with progress bar
alias cpv='rsync -ah --info=progress2'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    # alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Shorthand for programs
alias fd='fdfind'

# File explorer
# alias r='ranger'
alias r='lf'



# ---------------------------------------------------------------------- 
# GIT/YADM
# ---------------------------------------------------------------------- 
# git
# Ignore changes to already tracked files
alias untrack='git update-index --assume-unchanged'
alias retrack='git update-index --no-assume-unchanged'
alias backup-untracked='git ls-files --others --exclude-standard -z | xargs -0 tar rvf ~/backup-untracked.zip'
alias git-interactive='git add --interactive'
alias yadm-interactive='yadm add --interactive'



# ---------------------------------------------------------------------- 
# TOOLS
# ---------------------------------------------------------------------- 
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# "pi ip" Find my pi's IP address
alias piip='arp -na | grep -i b8:27:eb'

# For the XPS13
alias cctk=/opt/dell/dcc/cctk

alias audio-laptop='pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo'
# https://unix.stackexchange.com/questions/62818/how-can-i-switch-between-different-audio-output-hardware-using-the-shell
# alias audio-hdmi='pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo'
# xrandr --output <other screen> --same-as <main screen>

# Docker
# docker stop $(docker ps -a -q)
# docker rm $(docker ps -a -q)


# ---------------------------------------------------------------------- 
# RESTART & RELOAD
# ---------------------------------------------------------------------- 

# audio restart (from Ubuntu podcast)
alias restart-audio='systemctl --user restart pulseaudio'

# bad way to restart
# pulseaudio -k && sudo alsa force-reload
alias kill-slack='pkill slack'

# alias test-dunst='notify-send -u low "low urgency" ; notify-send -u normal "normal urgency" ;notify-send -u critical "critical urgency" ;'
# alias kill-dunst='killall dunst; notify-send -u low "low urgency" ; notify-send -u normal "normal urgency" ;notify-send -u critical "critical urgency" ;'
# Alias in alias
alias kill-dunst='killall dunst'

# Reload dusnt config file
# alias test-dunst='notify-send -u low "low urgency" ; notify-send -u normal "normal urgency" ;notify-send -u critical "critical urgency" ;'
# alias kill-dunst='killall dunst; notify-send -u low "low urgency" ; notify-send -u normal "normal urgency" ;notify-send -u critical "critical urgency" ;'
# Alias in alias
# alias kill-dunst='killall dunst; test-dunst'
alias dunst-reload='killall dunst           \
  && notify-send -u low "low urgency"       \
  && notify-send -u normal "normal urgency" \
  && notify-send -u critical "critical urgency"'
