#!/usr/bin/env bash
# ~/.bash_functions


# Variables
FEEDBACK_COLOR='\033[0;36m'
NO_COLOR='\033[0m'

# # For going inside running docker containers
# goinside(){
#     docker exec -it $1 bash -c "stty cols $COLUMNS rows $LINES && bash";
# }
# _goinside(){
#     COMPREPLY=( $(docker ps --format "{{.Names}}" -f name=$2) );
# }
# complete -F _goinside goinside;
# export -f goinside;


# Cronometer
alias crono='stf=$(date +%s.%N);for ((;;));do ctf=$( date +%s.%N );echo -en "\r$(date -u -d "0 $ctf sec - $stf sec" "+%H:%M:%S.%N")";done'



# Start a simple HTTP server on localhost:$port in the current working directory
function server() {
    local port="${1:-8000}"
    printf '\033[0;36m%s\033[0m\n' "Starting a py3 HTTP server for ${port}";
    python3 -m http.server "$port"
}

# run a file with one command per line using a pool of "P" workers
#
# It takes 1 mandatory argument:               pool /file/to/be/run.txt
#      and optionally, the worker count:       pool /file/to/be/run.txt 5
# TODO add a command and use a file of input args?
function pool() {
    local pcount="${2:-4}"
    local logfile=$(mktemp --suffix=.log)
    printf '\033[0;36m%s\033[0m\n' "Running the commands in ${1} with ${pcount} workers [LOGFILE AT ${logfile}]!";
    cat "${1}" | xargs -P "${pcount}" -I % sh -c '%' 2>&1 | tee ${logfile};
    printf '\033[0;36m%s\033[0m\n' "Finished running ${1} [LOGFILE AT ${logfile}]!";
}

# Create a python3 virtual environment with all of the standard reqs 
function py3venv() {
    local venvname="${1:-venv}"
    local venvdir="${2:-.}"
    
    printf '\033[0;36m%s\033[0m\n' "Making a py3 venv at ${venvname}!";
    (cd ${venvdir} \
    && mkdir ${venvname} \
    && python3 -m venv ${venvname}                                 \
    && ${venvname}/bin/python -m pip install --upgrade pip         \
    && ${venvname}/bin/python -m pip install --upgrade setuptools  \
    && ${venvname}/bin/python -m pip install --upgrade wheel       \
    && realpath ${venvdir} > $(find . -type d -name 'site-packages')/venv_parentdir.pth
  )

    printf '\033[0;36m%s\033[0m\n' "Done!";
}


# 
function pyprofile() {
    local scriptname="${1}"
    local basename=""${scriptname%.py}""
    
    printf '\033[0;36m%s\033[0m\n' "Running the profiler...";
    python -m cProfile -o ${basename}.stats ${scriptname}
    gprof2dot ${basename}.stats -f pstats > ${basename}.dot

    printf '\033[0;36m%s\033[0m\n' "Done!";
}


# function pdfmerge(){

#     local input_dir="${1:-.}"
#     local out_file="combined.pdf"

#     printf '\033[0;36m%s\033[0m\n' "Making a PDF with ${input_dir}/*.pdf -> ${out_file}!";

#     local tmp_dir=$(mktemp --directory --suffix=pdftk_unite)
#     local bookmarks_file="$tmp_dir/bookmarks.txt"
#     local bookmarks_fmt="BookmarkBegin
# BookmarkTitle: %s
# BookmarkLevel: 1
# BookmarkPageNumber: 1
# "

#     mkdir -p "${tmp_dir}"

#     for f in ${input_dir}/*.pdf; do
#         echo "Bookmarking $f..."
#         title="${f%.*}"
#         printf "$bookmarks_fmt" "$title" > "$bookmarks_file"
#         pdftk "$f" update_info "$bookmarks_file" output "$tmp_dir/$f"
#     done

#     pdftk "${tmp_dir}"/*.pdf cat output "$out_file"

# }



# # Prevent nested ranger instances
# ranger() {
#     if [ -z "$RANGER_LEVEL" ]; then
#         /usr/bin/ranger "$@"
#     else
#         exit
#     fi
# }
